import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://automationexercise.com/")
    try:
        page.get_by_role("button", name="Consent").click()
    except:
        pass
    page.get_by_role("link", name=" Signup / Login").click()
    page.get_by_role("textbox", name="Name").click()
    page.get_by_role("textbox", name="Name").fill("Shrinisha")
    page.locator("form").filter(has_text="Signup").get_by_placeholder("Email Address").click()
    page.locator("form").filter(has_text="Signup").get_by_placeholder("Email Address").fill("shrin2")
    page.get_by_role("button", name="Signup").click()
    page.locator("form").filter(has_text="Signup").get_by_placeholder("Email Address").click()
    page.locator("form").filter(has_text="Signup").get_by_placeholder("Email Address").fill("shrin2@gmail.com")
    page.get_by_role("button", name="Signup").click()
    expect(page.get_by_text("Enter Account Information")).to_be_visible()
    page.get_by_text("Enter Account Information").click()
    expect(page.get_by_text("Enter Account Information")).to_be_visible()
    page.get_by_role("radio", name="Mrs.").check()
    page.get_by_role("textbox", name="Password *").click()
    page.get_by_role("textbox", name="Password *").fill("nisha")
    page.locator("#days").select_option("12")
    page.locator("#months").select_option("12")
    page.locator("#years").select_option("2007")
    page.get_by_role("checkbox", name="Sign up for our newsletter!").check()
    page.get_by_role("checkbox", name="Receive special offers from").check()
    page.get_by_role("textbox", name="First name *").click()
    page.get_by_role("textbox", name="First name *").fill("Shrinisha")
    page.get_by_role("textbox", name="Last name *").click()
    page.get_by_role("textbox", name="Last name *").fill("Thoppe")
    page.get_by_role("textbox", name="Address * (Street address, P.").click()
    page.get_by_role("textbox", name="Address * (Street address, P.").fill("maatuthavani")
    page.get_by_role("textbox", name="State *").click()
    page.get_by_role("textbox", name="State *").fill("Tamil Nadu")
    page.get_by_role("textbox", name="City * Zipcode *").click()
    page.get_by_role("textbox", name="City * Zipcode *").fill("Madurai")
    page.locator("#zipcode").click()
    page.locator("#zipcode").fill("645321")
    page.get_by_role("textbox", name="Mobile Number *").click()
    page.get_by_role("textbox", name="Mobile Number *").fill("123456789")
    page.get_by_role("button", name="Create Account").click()
    expect(page.get_by_text("Account Created!")).to_be_visible()
    expect(page.locator("b")).to_contain_text("Account Created!")
    expect(page.get_by_role("link", name="Continue")).to_be_visible()
    page.get_by_role("link", name="Continue").click()
    page.get_by_role("link", name=" Logout").click()
    expect(page.locator("#form")).to_contain_text("Login to your account")
    page.get_by_role("heading", name="New User Signup!").click()
    expect(page.locator("#form")).to_contain_text("New User Signup!")
